server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: koreait2020
    

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 780471381876-pc3ne87u2n8ej7apkv5ii4f9ejge9pj4.apps.googleusercontent.com
            client-secret: j9szX-Hzh6rdncNmouRU1_GI
            scope:
            - email
            - profile